[project]
name = "fastmcp-axigen-email"
version = "0.1.0"
description = "MCP server for Axigen email operations"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastmcp>=0.2.0",
    "httpx>=0.27.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"